name: Close stale threads

on:
  schedule:
    - cron: "0 9 * * *" # daily at 09:00 UTC

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: >
            This issue has been marked stale due to inactivity. If this is still a problem,
            please add new details (logs, steps to reproduce) and we’ll revisit.
          close-issue-message: >
            Closing due to inactivity. If you can provide a fresh, reproducible case on the latest version,
            please open a new bug report with full details. Thanks!
          exempt-issue-labels: bug
